# Generated by Django 3.0.5 on 2020-05-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djaveS3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djaveS3.File')),
                ('resized_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('djaveS3.file',),
        ),
        migrations.CreateModel(
            name='TestPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djaveS3.Photo')),
                ('bucket_name', models.CharField(max_length=200)),
                ('next_keep_until', models.DateTimeField(null=True)),
                ('why_no_need_for_file', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('djaveS3.photo',),
        ),
    ]
