# Generated by Django 3.0.5 on 2020-05-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djaveS3', '0002_photo_testphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='signedfile',
            old_name='created_at',
            new_name='created',
        ),
    ]
